### ISSUE TITLE
Implement Header

### ISSUE THREAD

**Issue by andrewsgreene** [defenseunicorns/baffles-dashboard#9]
As a stakeholder, I want to see the baffles header, So that I know what product I'm using

## Acceptance Criteria

Given [Baffles Design](https://drive.google.com/drive/folders/1sxxaM9UFQOUuKGTEdhxv-qXkhmiHO4mx?usp=sharing)
When I open the baffles dashboard
Then I see the header as outlined by the design.

**Comment by mike-winberry** [comment]
### Tasks
- [ ] Create nav bar with proper blur and color
- [ ] Add lhs baffles icon
- [ ] Add rhs Airgap tag line
- [ ] configure background for body.
